### PR TITLE
Feature: Custom steps marker

### LINKED ISSUE #157: How to add style for slider steps ?
Hi every body,

I am looking for a way to add custom style to slider steps (e.g: 3 steps)

for example a small circle in each step 

Any solution for that ? 

Regards

### LINKED ISSUE #240: Is there a way to show Step Indicator?
Is there anyway i can show a dot or some bump or anything indicating the step position.

UseCase Example:

```
min = 1
max = 3
width = 200
```

The slider feels like it's not working until you slide 100px (while it's working just fine)

So Showing a far Step indicator will tell the user that he should slide that far to increase the value.

### LINKED ISSUE #514: How do i center thumbImage on top of step?
## Ask your Question

Is there any way to center the thumbImage above each step? 
At the moment based on which side it is of the slider (right or left based on middle value) it is tilting on that side. See images below. 

I cant seem to find any information on how to center the thumb based on the active step.

This is my code :

```
          <Slider
            minimumValue={minValue}
            maximumValue={maxValue}
            step={step}
            tapToSeek
            value={getValue()}
            onValueChange={(e) => handleChange(e)}
            onSlidingComplete={(e) => handleChange(e)}
            minimumTrackTintColor={Colors.default.lime}
            maximumTrackTintColor={Colors.default.lime}
            style={{ zIndex: 1, alignItems: 'center', justifyContent: 'center' }}
            thumbImage={require('../../assets/images/sliderThumb.png')}
          />
        </View>
        <View
          pointerEvents="none"
          style={{ justifyContent: 'space-between', flexDirection: 'row', top: -25, zIndex: 2 }}
        >
          {options.map((i, index) => {
            return (
              <View style={{ alignItems: 'center' }}>
                <SliderTrackMark key={index} isTrue={getValue() === i} />
                <Paragraph style={{ marginTop: 20, textAlign: 'center' }}>{i}</Paragraph>
              </View>
            );
          })}
        </View> 
```

Skärmavbild 2023-06-09 kl  12 53 45
Skärmavbild 2023-06-09 kl  12 55 21

### LINKED ISSUE #539: Slider with steps indicator, custom thumb component and more to come...
This issue (more like a summary/idea of what's to come) collects and implements several requests from our community folks (which is you, who is reading it):
#514 #240 #157 and #154

This means that Slider will soon be extended into a component with additional properties allowing to:
* turn on the steps indicators on the Slider's track
* use your own customized steps indicator
* use your own custom component for the thumb
* what else?

This will introduce a lot of changes, currently all of them are implemented in backward compatibility manner, so it's planned as v4.5.0. So, if you plan to use the Slider with default settings/props, do not worry, nothing will change. And if you want to use the customized steps indicator and stuff, please, give it a try as soon as it's released and provide me with some feedback.

But, before it's launched, there are basically two things you, community can do:
1. Check the work-in-progress branch: [feature/157/slider-steps-indicator](https://github.com/callstack/react-native-slider/compare/feature/157/slider-steps-indicator) to do some initial review, propose some improvement, or just play with the changes already
2. Leave a comment here, suggesting some other ideas, thoughts if you have any, or more importantly:
Suggest the API (props naming, props in general, usage, etc) for the upcoming feature.

Thank you for all the patience and support!

### PR DESCRIPTION
**Pull request by BartoszKlonowski**
This pull request closes #539 closes #240 closes #157 and fixes #514

It brings the custom steps indicator implementation to the Slider:

Android:

https://github.com/callstack/react-native-slider/assets/70535775/4940cb7f-faf3-486c-b5d4-eda0a94ff47b

iOS:

https://github.com/callstack/react-native-slider/assets/70535775/2c278f5a-2998-4e92-b63d-96762da75781

### CODE REVIEW

**Comment by BartoszKlonowski** [comment]
I feel like this is now completely ready.

**Comment by galih9** [comment]
hi, where do i found the documentation about this custom step marker feature?

**Comment by galih9** [comment]
i tried following the example app, but it keep showing

Property 'StepMarker' does not exist on type 'IntrinsicAttributes & SliderProps'.

**Comment by BartoszKlonowski** [comment]
Hello @galih9, thank you so much for checking!
Can you link how you use the `StepMarker` prop and the component you pass there?
Although I think I see the mistake in the Slider's code already, your info would still be very helpful 🙏

**Comment by rostyslav-broslavskyi** [comment]
@BartoszKlonowski Hello many thanks for such a big feature update 🔥

I want to ask when you plan on releasing this feature into `npm`?

**Comment by BartoszKlonowski** [comment]
Hello @rostyslav-broslavskyi, thank you very much for asking! :)
Well, I did have the plan to release it on a certain day, but there's much more to release it then I initially noticed, so now I only plan to release it as soon as possible and as soon as it's really ready - polished and bugles.
However, I'm of course still on it.
As for the question for any help - It's always **super helpful** to hear any feedback, so you are welcome to check out the main branch of this repo and play with the example app. Maybe modify some examples of the custom steps indicator and provide your thoughts (either here, or by creating new issue).
Thank you! 💪

**Comment by AyoCodess** [comment]
any progress on this?

**Comment by BartoszKlonowski** [comment]
@AyoCodess We are in progress o releasing it, once #581 is merged along with minor adjustments the whole feature will be public.
It takes a while to do those tiny step by step, so I'm hoping for a patience on those 🙏

**Pull request merged**
