### PR TITLE
Fix: move postinstall script to prepack

### PR DESCRIPTION
**Pull request by rborn**
Summary:
---------

Fixes https://github.com/callstack/react-native-slider/issues/430

Test Plan:
----------

Can't really test as it seems it needs to be packed first? I tried pointing to my fork, but it complains 😅

### CODE REVIEW

**Comment by BartoszKlonowski** [comment]
Thanks @rborn!
No worries, I'll test it and merge today or tomorrow.

**Review by BartoszKlonowski — APPROVED** [review]
Works as expected, thanks!

**Comment by samuelfreiberg** [comment]
When are new releases published? When will this fix be versioned? We're running into this same issue as well

**Comment by BartoszKlonowski** [comment]
@samuelfreiberg Please expect the release tomorrow (04.10).

**Pull request merged**
